<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Clinical notes auto-generated by AI
        Schema::create('clinical_documentation_intelligence', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('patient_id');
            $table->unsignedBigInteger('appointment_id')->nullable();
            $table->string('ai_session_id')->nullable();
            $table->enum('note_type', ['SOAP', 'progress', 'discharge', 'consultation', 'followup'])->default('progress');
            
            // Auto-generated sections
            $table->text('chief_complaint')->nullable();
            $table->text('history_of_present_illness')->nullable();
            $table->json('review_of_systems')->nullable();
            $table->text('physical_exam_findings')->nullable();
            $table->text('assessment')->nullable();
            $table->text('plan')->nullable();
            $table->text('medications_review')->nullable();
            
            // AI confidence scores
            $table->decimal('overall_confidence', 3, 2)->nullable();
            $table->json('section_confidences')->nullable();
            
            // Validation flags
            $table->decimal('completeness_score', 3, 2)->nullable();
            $table->json('compliance_flags')->nullable();
            $table->json('missing_elements')->nullable();
            
            // Integration
            $table->json('suggested_codes')->nullable(); // ICD-10, CPT suggestions
            $table->boolean('validated_by_doctor')->default(false);
            $table->timestamp('validated_at')->nullable();
            
            // Metadata
            $table->unsignedBigInteger('generated_from_transcription_id')->nullable();
            $table->timestamps();
            
            $table->foreign('patient_id')->references('id')->on('users');
            // Assuming appointments table exists, if not we might need to handle it
            // $table->foreign('appointment_id')->references('id')->on('appointments');
        });

        // Documentation quality metrics
        Schema::create('documentation_quality_metrics', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('clinical_doc_id');
            $table->enum('metric_type', ['completeness', 'accuracy', 'compliance', 'efficiency']);
            $table->decimal('score', 3, 2);
            $table->json('details')->nullable();
            $table->timestamps();
            
            $table->foreign('clinical_doc_id')->references('id')->on('clinical_documentation_intelligence')->onDelete('cascade');
        });

        // Suggested codes with validation
        Schema::create('suggested_codes', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('clinical_doc_id');
            $table->enum('code_type', ['ICD-10', 'CPT', 'SNOMED']);
            $table->string('code_value', 20);
            $table->text('code_description')->nullable();
            $table->decimal('confidence_score', 3, 2)->nullable();
            $table->boolean('is_validated')->default(false);
            $table->string('validated_by')->nullable();
            $table->timestamp('validated_at')->nullable();
            $table->timestamps();
            
            $table->foreign('clinical_doc_id')->references('id')->on('clinical_documentation_intelligence')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('suggested_codes');
        Schema::dropIfExists('documentation_quality_metrics');
        Schema::dropIfExists('clinical_documentation_intelligence');
    }
};
