<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>System Alert - MedCura AI</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 10px 10px 0 0;
        }
        .content {
            background: #f9f9f9;
            padding: 30px;
            border-radius: 0 0 10px 10px;
        }
        .alert {
            background: #f8d7da;
            border: 1px solid #f5c6cb;
            color: #721c24;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
        .issue {
            background: white;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid #dc3545;
            border-radius: 5px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 14px;
        }
        .timestamp {
            background: #e9ecef;
            padding: 10px;
            border-radius: 5px;
            font-family: monospace;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚨 System Alert</h1>
        <p>MedCura AI - Email System Monitoring</p>
    </div>
    
    <div class="content">
        <div class="alert">
            <strong>⚠️ Email System Issues Detected</strong><br>
            The automated monitoring system has detected {{ count($issues) }} issue(s) with the email system.
        </div>
        
        <h3>Issues Detected:</h3>
        @foreach($issues as $issue)
        <div class="issue">
            <strong>•</strong> {{ $issue }}
        </div>
        @endforeach
        
        <h3>System Information:</h3>
        <div class="timestamp">
            <strong>Timestamp:</strong> {{ $timestamp }}<br>
            <strong>Server:</strong> {{ $server }}<br>
            <strong>Environment:</strong> {{ config('app.env') }}<br>
            <strong>Application:</strong> {{ config('app.name') }}
        </div>
        
        <h3>Recommended Actions:</h3>
        <div class="issue">
            1. Check the application logs: <code>storage/logs/laravel.log</code>
        </div>
        <div class="issue">
            2. Verify email configuration in <code>.env</code> file
        </div>
        <div class="issue">
            3. Test email connectivity: <code>php artisan email:health-check</code>
        </div>
        <div class="issue">
            4. Check SMTP server status and credentials
        </div>
        <div class="issue">
            5. Verify DNS records (SPF, DMARC, MX)
        </div>
        
        <p><strong>This is an automated alert.</strong> Please investigate and resolve the issues as soon as possible to ensure uninterrupted email delivery.</p>
    </div>
    
    <div class="footer">
        <p>This alert was generated by the MedCura AI monitoring system.</p>
        <p>To disable these alerts, modify the monitoring configuration.</p>
        <p><small>© {{ date('Y') }} MedCura AI. All rights reserved.</small></p>
    </div>
</body>
</html>