<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class AlertRule extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'event_type',
        'model_type',
        'conditions',
        'severity_config',
        'escalation_rules',
        'notification_channels',
        'is_active',
        'priority',
        'cooldown_minutes',
        'metadata',
    ];

    protected $casts = [
        'conditions' => 'array',
        'severity_config' => 'array',
        'escalation_rules' => 'array',
        'notification_channels' => 'array',
        'is_active' => 'boolean',
        'metadata' => 'array',
    ];

    /**
     * Get alerts generated by this rule
     */
    public function alerts(): HasMany
    {
        return $this->hasMany(Alert::class);
    }

    /**
     * Scope for active rules
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope for rules by event type
     */
    public function scopeByEventType($query, string $eventType)
    {
        return $query->where('event_type', $eventType);
    }

    /**
     * Scope for rules by model type
     */
    public function scopeByModelType($query, string $modelType)
    {
        return $query->where('model_type', $modelType);
    }

    /**
     * Scope ordered by priority
     */
    public function scopeOrderedByPriority($query)
    {
        return $query->orderBy('priority', 'desc');
    }

    /**
     * Check if conditions match the given data
     */
    public function matchesConditions(array $data): bool
    {
        $conditions = $this->conditions;

        if (empty($conditions)) {
            return true; // No conditions means always match
        }

        return $this->evaluateConditions($conditions, $data);
    }

    /**
     * Evaluate conditions recursively
     */
    protected function evaluateConditions(array $conditions, array $data): bool
    {
        $operator = $conditions['operator'] ?? 'AND';

        if (isset($conditions['conditions'])) {
            // Nested conditions
            $results = [];
            foreach ($conditions['conditions'] as $condition) {
                $results[] = $this->evaluateConditions($condition, $data);
            }

            return $operator === 'AND' ? !in_array(false, $results) : in_array(true, $results);
        }

        // Single condition
        return $this->evaluateSingleCondition($conditions, $data);
    }

    /**
     * Evaluate a single condition
     */
    protected function evaluateSingleCondition(array $condition, array $data): bool
    {
        $field = $condition['field'];
        $operator = $condition['operator'];
        $value = $condition['value'];

        $fieldValue = data_get($data, $field);

        switch ($operator) {
            case 'equals':
                return $fieldValue == $value;
            case 'not_equals':
                return $fieldValue != $value;
            case 'contains':
                return str_contains((string)$fieldValue, (string)$value);
            case 'not_contains':
                return !str_contains((string)$fieldValue, (string)$value);
            case 'greater_than':
                return $fieldValue > $value;
            case 'less_than':
                return $fieldValue < $value;
            case 'greater_equal':
                return $fieldValue >= $value;
            case 'less_equal':
                return $fieldValue <= $value;
            case 'in':
                return in_array($fieldValue, (array)$value);
            case 'not_in':
                return !in_array($fieldValue, (array)$value);
            case 'regex':
                return preg_match($value, (string)$fieldValue);
            default:
                return false;
        }
    }

    /**
     * Get severity level based on data
     */
    public function getSeverityLevel(array $data): string
    {
        $config = $this->severity_config;

        if (empty($config)) {
            return 'medium';
        }

        foreach ($config as $level => $thresholds) {
            if ($this->matchesSeverityThresholds($thresholds, $data)) {
                return $level;
            }
        }

        return 'medium'; // default
    }

    /**
     * Check if data matches severity thresholds
     */
    protected function matchesSeverityThresholds(array $thresholds, array $data): bool
    {
        foreach ($thresholds as $field => $condition) {
            if (!$this->evaluateSingleCondition([
                'field' => $field,
                'operator' => $condition['operator'],
                'value' => $condition['value']
            ], $data)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Get escalation rules for a severity level
     */
    public function getEscalationRules(string $severity): array
    {
        return $this->escalation_rules[$severity] ?? $this->escalation_rules['default'] ?? [];
    }

    /**
     * Check if rule is in cooldown period
     */
    public function isInCooldown(): bool
    {
        if ($this->cooldown_minutes <= 0) {
            return false;
        }

        $lastAlert = $this->alerts()
            ->where('created_at', '>=', now()->subMinutes($this->cooldown_minutes))
            ->first();

        return $lastAlert !== null;
    }
}
